We are now goint to use Keras to do the same thing as before. As we will see, this is are just one liners.

In [1]:
from keras.models import Sequential
from keras.layers import SimpleRNN, LSTM, GRU
import numpy as np

Using TensorFlow backend.


We have the data

In [ ]:
X_data = [[0,0,1,0],[0,1,0,0],[1,0,0,1]]
y_data= [[-1,1,-1,-1],[1,-1,-1,1],[-1,-1,1,-1]]
X_data=np.array(X_data).reshape(12,1,1)
y_data=np.array(y_data).reshape(12,1)

The first thing is to create a model.

In [2]:
model_rnn=Sequential()

then we add the layer that we want

In [3]:
model_rnn.add(SimpleRNN(1,input_shape=(1,1)))

In [5]:
model_rnn.compile(loss='mean_squared_error',optimizer='Adam')

In [9]:
model_rnn.predict(np.array([[[0]],[[1]]]))

array([[ 0.        ],
       [ 0.08411049]], dtype=float32)

In [11]:
model_rnn.fit(X_data, y_data, epochs=1000,verbose=False);

In [12]:
model_rnn.predict(np.array([[[0]],[[1]]]))

array([[-0.14393935],
       [-0.61789715]], dtype=float32)

and we can do the same for LSTM and GRU

In [15]:
model_LSTM=Sequential()
model_LSTM.add(SimpleRNN(1,input_shape=(1,1)))
model_LSTM.compile(loss='mean_squared_error',optimizer='Adam')

In [16]:
model_LSTM.predict(np.array([[[0]],[[1]]]))

array([[ 0.        ],
       [-0.67661542]], dtype=float32)

In [21]:
model_LSTM.fit(X_data, y_data, epochs=1000,verbose=False);

In [20]:
model_LSTM.predict(np.array([[[0]],[[1]]]))

array([[-0.00117429],
       [-0.96919465]], dtype=float32)

In [42]:
X_data = [[0,0,1,0],[0,1,0,0],[1,0,0,1]]
y_data= [[-1,1,-1,-1],[1,-1,-1,1],[-1,-1,1,-1]]
X_data=np.array(X_data).reshape(3,4,1)
y_data=np.array(y_data).reshape(3,4,1)

** Exercise: ** Do the same for GRU

A natural question to ask is, how does this work in the backend? how does it unroll? Can I work with sequences instead of just one element at the time. Next, we show how to get the sequences

In [40]:
model_=Sequential()
model_.add(SimpleRNN(1,input_shape=(4,1),unroll=True,return_sequences=True))
model_.compile(loss='mean_squared_error',optimizer='Adam')

In [41]:
model_.predict(np.array([[[0],[0],[1],[0]]]))

array([[[ 0.        ],
        [ 0.        ],
        [-0.62055606],
        [-0.5515151 ]]], dtype=float32)

In [44]:
model_.fit(X_data,y_data,verbose=False,epochs=1000);

In [45]:
model_.predict(np.array([[[0],[0],[1],[0]]]))

array([[[ 0.30338496],
        [ 0.48682559],
        [-0.76398802],
        [-0.23299932]]], dtype=float32)

We finish with a a comment about building recurrent nueral network, it is a common (and quite good) idea to create the recurrent networks as taking not just the last term as input, but the last some number of times. This makes the network to have better performance.